name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  PNPM_VERSION: 10.0.0
  NODE_VERSION: 20
  NEXT_TELEMETRY_DISABLED: '1'

jobs:
  node-quality:
    name: ${{ matrix.display }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [lint, typecheck, test]
        include:
          - task: lint
            display: Lint
          - task: typecheck
            display: Typecheck
          - task: test
            display: Unit tests
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ${{ matrix.display }}
        run: pnpm ${{ matrix.task }}

  accessibility:
    name: Accessibility
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build portal
        run: pnpm --filter @airnub/portal build

      - name: Start portal server
        run: |
          pnpm --filter @airnub/portal start -- --hostname 0.0.0.0 --port 3000 &
          echo $! > portal.pid

      - name: Wait for portal
        run: pnpm dlx wait-on http://127.0.0.1:3000

      - name: Run Cypress axe suite
        run: pnpm --filter @airnub/portal test:a11y

      - name: Run pa11y regression suite
        run: pnpm --filter @airnub/portal test:pa11y

      - name: Stop portal server
        if: always()
        run: |
          if [ -f portal.pid ]; then
            kill $(cat portal.pid)
          fi

  temporal-worker:
    name: Temporal worker lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint Temporal worker bundle
        run: pnpm --filter @airnub/orchestrator-temporal lint

  database:
    name: Database policies
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Dry-run database migrations
        run: pnpm --filter @airnub/db run migrate --dry-run

      - name: Check Supabase RLS policies
        run: node packages/db/check-rls.mjs

  docs-links:
    name: Documentation links
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check Markdown links
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --no-progress
            --markdown
            --base .
            ./AGENTS.md
            './docs/**/*.md'
