name: Policy Guards
on: [pull_request]
jobs:
  rls-guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Detect forbidden tenancy gates
        run: |
          set -euo pipefail
          mapfile -d '' matches < <(
            grep -RPzl --include='*.sql' \
              'create\s+policy[\s\S]{0,200}(org_id|tenant_org_id)\s+is\s+null' \
              packages/db/migrations supabase/migrations || true
          )

          if (( ${#matches[@]} )); then
            printf '%s\n' "${matches[@]}"
            echo "Forbidden tenancy gate via IS NULL detected in SQL policies." >&2
            exit 1
          fi
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies (no scripts)
        run: pnpm install --ignore-scripts
      - name: Run tenancy smoke checks
        run: pnpm test:rls-smoke
