name: Policy Guards
on: [pull_request]
jobs:
  rls-guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Check RLS bad patterns
        run: |
          set -euo pipefail
          # Fail if any policy uses tenancy gates relying on org/tenant columns being NULL
          mapfile -d '' matches < <(
            grep -RPzl --include='*.sql' \
              'create\s+policy[\s\S]{0,200}(org_id|tenant_org_id)\s+is\s+null' \
              packages/db/migrations || true
          )

          if (( ${#matches[@]} )); then
            printf '%s\n' "${matches[@]}"
            echo "Forbidden tenancy gate via IS NULL detected in SQL policies." >&2
            exit 1
          fi
      - name: Block client writes to platform.*
        run: |
          # Adjust app paths if needed
          if grep -RinE "from\\(['\"\"]platform\\." apps/ -n | grep -E "insert|update|upsert|delete"; then
            echo "Client write to platform.* detected." >&2
            exit 1
          fi
